ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS invoice VARCHAR(255),
ADD COLUMN IF NOT EXISTS track_number VARCHAR(255),
ADD COLUMN IF NOT EXISTS cargo_type VARCHAR(255),
ADD COLUMN IF NOT EXISTS cargo_weight VARCHAR(100),
ADD COLUMN IF NOT EXISTS notes TEXT;