ALTER TABLE clients 
ADD COLUMN IF NOT EXISTS ogrn VARCHAR(15),
ADD COLUMN IF NOT EXISTS postal_address TEXT,
ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS account_number VARCHAR(20),
ADD COLUMN IF NOT EXISTS bik VARCHAR(9),
ADD COLUMN IF NOT EXISTS corr_account VARCHAR(20);